---
stages:
  - lint
  - prove


default:
  interruptible: true    # allow new pushes to cancel running pipelines


# do not run pipelines for MRs additionally to branch pipelines
.no-merge-request-pipelines: &no-merge-request-pipelines
  if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  when: never


.manual: &manual
  - when: manual
    allow_failure: true    # do not block pipeline


lint:
  stage: lint
  rules:    # some rule required if any other job has 'rules:'
    - *no-merge-request-pipelines
    - when: on_success    # GitLab default
  image:
    name: alpine/git:latest
    entrypoint: [""]    # override default entrypoint "git"
  script:
    - "# Listing any text files containing CR characters:"
    - sh -c "! git grep -IlP '\x0d'"
    - "# Listing any text files containing TAB characters:"
    - sh -c "! git grep -IlP '\x09'"
    - "# Listing any text files with trailing whitespace:"
    - sh -c "! git grep -Il '[[:blank:]]$'"
    - "# Listing any text files without trailing newline (except external libs):"
    - sh -c 'git grep -Il "" | grep -v ^root/static/lib/ | while read file; do test "$( tail -c1 "$file" )" && echo "$file"; done | tee >( cat >&2 ) | [ $(wc -c) -eq 0 ]'


.make-test:
  stage: prove
  image: perl:$PERL_VERSION
  cache:
    key: perl-$PERL_VERSION-local-lib-shared-between-all-branches
    paths: [perl5/]
    unprotect: true    # share between protected/unprotected branches
  before_script:
    # install and activate local::lib, possibly also install Devel::Cover
    - 'PERL5LIB=perl5/lib/perl5/ cpanm --notest --local-lib perl5/ local::lib $( [ -n "$INSTALL_DEVEL_COVER" ] && echo Devel::Cover )'
    - 'eval "$( perl -Iperl5/lib/perl5/ -Mlocal::lib=perl5/ )"'

    # install our dependencies
    - 'cpanm --notest --installdeps --with-configure $( [ -n "$AUTHOR_TESTING" ] && echo --with-develop --with-recommends ) .'
  script:
    - perl Makefile.PL
    - make
    - make test


# minimal supported Perl version (without author testing/coverage, only for master)
perl-5.32:
  extends: .make-test
  rules:
    - *no-merge-request-pipelines
    - if: $CI_COMMIT_REF_NAME == "master"
    - *manual
  variables:
    PERL_VERSION: '5.32'


# latest supported Perl version (without coverage, not for master)
perl-5.38:
  extends: .make-test
  rules:
    - *no-merge-request-pipelines
    - if: $CI_COMMIT_REF_NAME != "master"
    - *manual
  services:
    - name: postgres:bookworm
  variables:
    AUTHOR_TESTING: '1'
    PERL_VERSION: '5.38'
    POSTGRES_PASSWORD: coocook    # for "postgres" setup
    PGHOST:            postgres   # for DBD::Pg
    PGUSER:            postgres
    PGPASSWORD:        coocook


# latest supported Perl version
perl-5.38+coverage:
  extends: perl-5.38
  rules:    # some rule required if any other job has 'rules:'
    - *no-merge-request-pipelines
    - if: $CI_COMMIT_REF_NAME == "master"
    - *manual
  variables:
    INSTALL_DEVEL_COVER: '1'
  script:
    - perl Makefile.PL
    - AUTHOR_TESTING=1 cover -ignore_re ^perl5/ -ignore_re SHSchema -make 'make TEST_VERBOSE=1' -test
  coverage: '/^Total .+ (\d+\.\d+)$/'
